### ISSUE TITLE
Add NPU code and unit mappings

### ISSUE THREAD

**Issue by tomersagi** [ohdsi-denmark/danish_medical_vocabularies_to_OMOP#1]
- [x] Add an NPU to LOINC csv file
- [x] Add a DNK to LOINC csv file 
- [x] Add an NPU to UCUM/LOINC csv file
- [x] Add a DNK to UCUM/LOINC csv file
- [x] Add the value-as-text mapping from the schema matching file for Lab Tests

**Comment by Yaqoob-eng** [comment]
Tasks completed
